experiment:
  name: train_regid
  output_dir: ./outputs/train_regid_mask05_dt10
data:
  data_dir: /work/goet1019/dataset/mip_nerf360/3dgs_camera_pose/bicycle
  image_folder: images_4
  mask_folder: wheel_masks_rendered
  sparse_folder: sparse/0

model:
  gt_ply_path: /work/goet1019/sam-3d-objects/lab_test_for_python/some_basic_pointcloud/onlywheel_gt.ply
  sam3d_ply_path: /work/goet1019/sam-3d-objects/lab_test_for_python/some_basic_pointcloud/onlywheel_sam3d.ply



training:
  device: cuda
  iterations: 9800
  batch_size: 1
  num_workers: 4
  save_every: 10


optimizer:
  lr_translation: 0.001
  lr_rotation: 0.0005
  lr_scale: 0.0001
  eps: 1.0e-15


loss:
  use_photo: false
  lambda_photo: 1.0
  lambda_dssim: 0.2
  disable_ssim: false

  use_arap: false
  lambda_arap: 1.0
  arap_type: both
  normalized_arap: true

  use_mask: true
  lambda_mask: 0.5
  lambda_mask_l1: 1
  lambda_mask_iou: 1

  use_dt: true
  lambda_dt: 10


loss_balance:
  enabled: false
  mode: contribution
  photo_target: 0.5
  arap_target: 0.5
  mask_target: 0.5
  dt_target: 0.5
  
  eps: 1.0e-8
  min_weight: 1.0e-4
  max_weight: 100.0

debug:
  save_ply: true
  save_images: true
  save_graph_ply: false
  